### ISSUE TITLE
Main Activity:

### ISSUE THREAD

**Issue by alex-ander** [PhilippMa/MCATeam6#1]
- [x] Fragment for camera
- [x] Menu on the bottom (Bottom Navigation View)
- [ ] Implementation depends on ML Kit features (full screen camera should be possible)
- [ ] Later: Integration of image recognition

**Comment by yoona3316** [comment]
styles for bottom nav is not yet applied.

**Comment by yoona3316** [comment]
- [x] bug: app dies when switching to other fragment after applying camerax
